#Makefile

SOURCE_FILES= \
             $(CONVECT)/acmcld.f90 \
             $(CONVECT)/buoyancy.f90 \
             $(CONVECT)/cuparm_driver.f90 \
             $(CONVECT)/mem_cuparm.f90 \
             $(CONVECT)/module_bl_acm2.f90 \
             $(CONVECT)/module_cu_emanuel.f90 \
             $(CONVECT)/module_cu_g3.f90 \
             $(CONVECT)/module_cu_gf.f90 \
             $(CONVECT)/module_cu_kfeta.f90 \
             $(CONVECT)/module_cu_tiedtke.f90 \
             $(CONVECT)/pbl_driver.f90 \
             $(CONVECT)/smagorinsky.f90 \
             ../interp_to_ll/fields2_ll.F90 \
             $(LEAF)/leaf4.F90 \
             $(LEAF)/leaf4_canopy.f90 \
             $(LEAF)/leaf4_coms.f90 \
             $(LEAF)/leaf4_database_read.f90 \
             $(LEAF)/leaf4_init_atm.f90 \
             $(LEAF)/leaf4_landcell.f90 \
             $(LEAF)/leaf4_plot.f90 \
             $(LEAF)/leaf4_sfcwater.f90 \
             $(LEAF)/leaf4_soil.f90 \
             $(LEAF)/leaf4_startup.f90 \
             $(LEAF)/mem_leaf.f90 \
             $(LEAF)/ndvi_database_read.f90 \
             $(LEAF)/olam_mpi_land.F90 \
             $(LEAF)/para_init_land.f90 \
             $(LEAF)/read_soil_analysis.F90 \
             $(MODEL_MODS)/consts_coms.f90 \
             $(MODEL_MODS)/ke_coms.f90 \
             $(MODEL_MODS)/massflux.f90 \
             $(MODEL_MODS)/max_dims.f90 \
             $(MODEL_MODS)/mem_addsc.f90 \
             $(MODEL_MODS)/mem_adv.f90 \
             $(MODEL_MODS)/mem_average_vars.f90 \
             $(MODEL_MODS)/mem_basic.f90 \
             $(MODEL_MODS)/mem_flux_accum.f90 \
             $(MODEL_MODS)/mem_grid.f90 \
             $(MODEL_MODS)/mem_ijtabs.f90 \
             $(MODEL_MODS)/mem_mclat.f90 \
             $(MODEL_MODS)/mem_micro.f90 \
             $(MODEL_MODS)/mem_mksfc.f90 \
             $(MODEL_MODS)/mem_nudge.f90 \
             $(MODEL_MODS)/mem_para.F90 \
             $(MODEL_MODS)/mem_plot.f90 \
             $(MODEL_MODS)/mem_rayf.f90 \
             $(MODEL_MODS)/mem_sflux.f90 \
             $(MODEL_MODS)/mem_tend.f90 \
             $(MODEL_MODS)/mem_thuburn.f90 \
             $(MODEL_MODS)/mem_timeavg.f90 \
             $(MODEL_MODS)/mem_turb.f90 \
             $(MODEL_MODS)/mem_zonavg.f90 \
             $(MODEL_MODS)/micro_coms.f90 \
             $(MODEL_MODS)/misc_coms.f90 \
             $(MODEL_MODS)/olam_mpi_atm.F90 \
             $(MODEL_MODS)/oname_coms.f90 \
             $(MODEL_MODS)/oplot_coms.f90 \
             $(MODEL_MODS)/plotcolors.f90 \
             $(MODEL_MODS)/var_tables.f90 \
             $(OISAN)/asti.f90 \
             $(OISAN)/astp.F90 \
             $(OISAN)/file_inv.f90 \
             $(OISAN)/fldsisan.f90 \
             $(OISAN)/isan_coms.f90 \
             $(OISAN)/isan_driver.f90 \
             $(OISAN)/obs_nudge.f90 \
             $(OISAN)/spec_nudge.f90 \
             $(OMODEL)/alloc.f90 \
             $(OMODEL)/average_vars.f90 \
             $(OMODEL)/cartesian.f90 \
             $(OMODEL)/cart_hex.f90 \
             $(OMODEL)/coneplot.f90 \
             $(OMODEL)/contslab.F90 \
             $(OMODEL)/fill_itabs.f90 \
             $(OMODEL)/history_start.f90 \
             $(OMODEL)/history_write.f90 \
             $(OMODEL)/icosahedron.f90 \
             $(OMODEL)/makesfc.f90 \
             $(OMODEL)/obnd.f90 \
             $(OMODEL)/ocio.f90 \
             $(OMODEL)/ohhi.f90 \
             $(OMODEL)/olam_grid.f90 \
             $(OMODEL)/olammain.F90 \
             $(OMODEL)/olamplot.f90 \
             $(OMODEL)/olam_run.F90 \
             $(OMODEL)/olhi.f90 \
             $(OMODEL)/omic_coll.f90 \
             $(OMODEL)/omic_driv.f90 \
             $(OMODEL)/omic_gamma.f90 \
             $(OMODEL)/omic_init.f90 \
             $(OMODEL)/omic_misc.f90 \
             $(OMODEL)/omic_nuc.f90  \
             $(OMODEL)/omic_tabs.f90 \
             $(OMODEL)/omic_vap.f90 \
             $(OMODEL)/oname_check.f90 \
             $(OMODEL)/oname.f90 \
             $(OMODEL)/oplot_interface.F90 \
             $(OMODEL)/oplot_lib.f90 \
             $(OMODEL)/othrm.f90 \
             $(OMODEL)/para_decomp.f90 \
             $(OMODEL)/perim_fill.f90 \
             $(OMODEL)/spawn_nest.f90 \
             $(OMODEL)/spring_dynamics.f90 \
             $(OMODEL)/surface_fluxes.F90 \
             $(OMODEL)/thiltend_long.f90 \
             $(OMODEL)/tileslab.F90 \
             $(OMODEL)/topo_database_read.f90 \
             $(OMODEL)/triangle_utils.f90 \
             $(OMODEL)/vectslab.F90 \
             $(OMODEL)/vel_t3d.f90 \
             $(OMODEL)/hex_grid.f90 \
             $(OMODEL)/para_init_hex.f90 \
             $(OMODEL)/prog_wrtv_hex.f90 \
             $(OMODEL)/scalar_transport_hex.f90 \
             $(OMODEL)/timestep_hex.f90 \
             $(OMODEL)/tri_grid.f90 \
             $(OUTILS)/blas.f90 \
             $(OUTILS)/check_nans.F90 \
             $(OUTILS)/dateutils.f90 \
             $(OUTILS)/hdf5_f2f.F90 \
             $(OUTILS)/hdf5_utils.F90 \
             $(OUTILS)/interp_lib.f90 \
             $(OUTILS)/lapack.f90 \
             $(OUTILS)/map_proj.f90 \
             $(OUTILS)/o_ncar.f90 \
	     $(OUTILS)/polygon_overlap.f90 \
             $(OUTILS)/read_cdc.f90 \
             $(OUTILS)/quadrature.f90 \
             $(OUTILS)/string_lib.f90 \
             $(OUTILS)/sys_utils.f90 \
             $(OUTILS)/therm_lib.f90 \
             $(OUTILS)/tridiag_lib.f90 \
             $(RADIATE)/harr_raddriv.f90 \
             $(RADIATE)/harr_rad.f90 \
             $(RADIATE)/harr_radinit.f90 \
             $(RADIATE)/mem_harr.f90 \
             $(RADIATE)/mem_radiate.f90 \
             $(RADIATE)/rad_driv.F90 \
             $(RADIATE)/rad_mclat.f90 \
             $(RADIATE)/rrtmg_cloud_optics.f90 \
             $(RADIATE)/rrtmg_raddriv.f90 \
             $(RADIATE)/rrtmg_lw/mcica_random_numbers.f90 \
             $(RADIATE)/rrtmg_lw/mcica_subcol_gen_lw.f90 \
             $(RADIATE)/rrtmg_lw/parkind.f90 \
             $(RADIATE)/rrtmg_lw/parrrtm.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_cld.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_con.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg01.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg02.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg03.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg04.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg05.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg06.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg07.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg08.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg09.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg10.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg11.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg12.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg13.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg14.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg15.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg16.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_ncpar.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_ref.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_tbl.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_vsn.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_wvn.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_cldprmc.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_cldprop.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_init.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_rad.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_rad_nomcica.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_read_h5.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_rtrn.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_rtrnmc.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_rtrnmr.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_setcoef.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_taumol.f90 \
             $(RADIATE)/rrtmg_sw/mcica_subcol_gen_sw.f90 \
             $(RADIATE)/rrtmg_sw/parrrsw.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_aer.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_cld.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_con.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg16.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg17.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg18.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg19.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg20.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg21.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg22.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg23.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg24.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg25.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg26.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg27.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg28.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg29.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_ncpar.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_ref.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_tbl.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_vsn.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_wvn.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_cldprmc.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_cldprop.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_init.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_rad.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_rad_nomcica.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_read_h5.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_reftra.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_setcoef.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_spcvmc.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_spcvrt.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_taumol.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_vrtqdr.f90 \
             $(SEA)/mem_sea.f90 \
             $(SEA)/olam_mpi_sea.F90 \
             $(SEA)/para_init_sea.f90 \
             $(SEA)/read_seaice_analysis.F90 \
             $(SEA)/read_sst_analysis.F90 \
             $(SEA)/sea_coms.f90 \
             $(SEA)/sea.f90 \
             $(SEA)/seaice_database_read.f90 \
             $(SEA)/seaice.f90 \
             $(SEA)/sea_init_atm.f90 \
             $(SEA)/sea_startup.f90 \
             $(SEA)/sst_database_read.f90 \
             $(HURRICANE)/hurricane_init.f90 \
             $(TEST_CASES)/mem_swtc5_refsoln_cubic.f90 \
             $(TEST_CASES)/swtc_init.f90 \
             $(TEST_CASES)/diagn_global_swtc.F90
