# OLAM root directory.

OLAM_ROOT=..

# Versions.

OLAM_VERSION=7.0

# Source directories.

MODEL_MODS=$(OLAM_ROOT)/modules
OMODEL=$(OLAM_ROOT)/omodel
OISAN=$(OLAM_ROOT)/oisan
CONVECT=$(OLAM_ROOT)/convect
LAKE=$(OLAM_ROOT)/lake
LAND=$(OLAM_ROOT)/land
LEAF=$(OLAM_ROOT)/leaf
SFCG=$(OLAM_ROOT)/sfcgrid
SEA=$(OLAM_ROOT)/sea
OUTILS=$(OLAM_ROOT)/outils
RADIATE=$(OLAM_ROOT)/radiate
UMWM=$(OLAM_ROOT)/UMWM
HURRICANE=$(OLAM_ROOT)/hurricane
LAGPART=$(OLAM_ROOT)/lagpart
TEST_CASES=$(OLAM_ROOT)/test_cases
CMAQ=$(OLAM_ROOT)/CMAQ
MEGAN=$(OLAM_ROOT)/MEGAN
