#Makefile

SOURCE_FILES= \
             $(CONVECT)/buoyancy.f90 \
             $(CONVECT)/cuparm_driver.f90 \
             $(CONVECT)/mem_cuparm.f90 \
             $(CONVECT)/mem_turb.f90 \
             $(CONVECT)/module_bl_acm2.f90 \
             $(CONVECT)/module_cu_emanuel.f90 \
             $(CONVECT)/module_cu_g3.f90 \
	     $(CONVECT)/module_cu_g3_aq.f90 \
             $(CONVECT)/module_cu_g3_tracer.f90 \
             $(CONVECT)/module_cu_kfeta.f90 \
             $(CONVECT)/module_cu_tiedtke.f90 \
             $(CONVECT)/pbl_driver.f90 \
             $(CONVECT)/smagorinsky.f90 \
             $(LAKE)/lake.f90 \
             $(LAKE)/lake_coms.f90 \
             $(LAKE)/lake_init_atm.f90 \
             $(LAKE)/lake_startup.f90 \
             $(LAKE)/mem_lake.f90 \
             $(LAND)/glhymps_read.f90 \
             $(LAND)/land_database_read.f90 \
             $(LAND)/leaf4_canopy.f90 \
             $(LAND)/leaf4_coms.f90 \
             $(LAND)/leaf4_init_atm.f90 \
             $(LAND)/leaf4_plot.f90 \
             $(LAND)/leaf4_surface.f90 \
             $(LAND)/leaf4_soil.f90 \
             $(LAND)/land_startup.f90 \
             $(LAND)/mem_land.f90 \
             $(LAND)/ndvi_database_read.f90 \
             $(LAND)/read_soil_analysis.F90 \
             $(LAND)/soilgrids_read.f90 \
             $(MODEL_MODS)/consts_coms.f90 \
             $(MODEL_MODS)/max_dims.f90 \
             $(MODEL_MODS)/mem_addgrid.f90 \
             $(MODEL_MODS)/mem_addsc.f90 \
             $(MODEL_MODS)/mem_adv.f90 \
             $(MODEL_MODS)/mem_average_vars.f90 \
             $(MODEL_MODS)/mem_basic.f90 \
             $(MODEL_MODS)/mem_co2.f90 \
             $(MODEL_MODS)/mem_delaunay.f90 \
             $(MODEL_MODS)/mem_flux_accum.f90 \
             $(MODEL_MODS)/mem_grid.f90 \
             $(MODEL_MODS)/mem_ijtabs.f90 \
             $(MODEL_MODS)/mem_micro.f90 \
             $(MODEL_MODS)/mem_para.F90 \
             $(MODEL_MODS)/mem_plot.f90 \
             $(MODEL_MODS)/mem_rayf.f90 \
             $(MODEL_MODS)/mem_tend.f90 \
             $(MODEL_MODS)/mem_zonavg.f90 \
             $(MODEL_MODS)/micro_coms.f90 \
             $(MODEL_MODS)/misc_coms.f90 \
             $(MODEL_MODS)/nuclei_coms.f90 \
             $(MODEL_MODS)/oname_coms.f90 \
             $(MODEL_MODS)/oplot_coms.f90 \
             $(MODEL_MODS)/plotcolors.f90 \
             $(MODEL_MODS)/var_tables.f90 \
             $(OISAN)/asti.f90 \
             $(OISAN)/astp.F90 \
             $(OISAN)/file_inv.f90 \
             $(OISAN)/init_nudgrid.f90 \
             $(OISAN)/isan_coms.f90 \
             $(OISAN)/isan_driver.f90 \
             $(OISAN)/mem_nudge.f90 \
             $(OISAN)/nudge_o3.f90 \
             $(OISAN)/obs_nudge.f90 \
             $(OISAN)/olam_mpi_nudge.F90 \
             $(OISAN)/spec_nudge.f90 \
             $(OMODEL)/alloc.f90 \
             $(OMODEL)/average_vars.f90 \
             $(OMODEL)/cart_hex.f90 \
             $(OMODEL)/coneplot.f90 \
             $(OMODEL)/contslab.F90 \
             $(OMODEL)/expand_global.f90 \
             $(OMODEL)/fields3_ll.F90 \
             $(OMODEL)/fill_itabs.f90 \
             $(OMODEL)/grad_lib.f90 \
             $(OMODEL)/hex_grid.f90 \
             $(OMODEL)/history_start.f90 \
             $(OMODEL)/history_write.f90 \
             $(OMODEL)/icosahedron.f90 \
             $(OMODEL)/init_atmgrid.f90 \
             $(OMODEL)/lateral_friction.f90 \
             $(OMODEL)/les_diag.F90 \
             $(OMODEL)/lite_vars.f90 \
             $(OMODEL)/nuclei_deposition.f90 \
             $(OMODEL)/obnd.f90 \
             $(OMODEL)/ocio.f90 \
             $(OMODEL)/ohhi.f90 \
             $(OMODEL)/olam_grid.f90 \
             $(OMODEL)/olam_mpi_atm.F90 \
             $(OMODEL)/olammain.F90 \
             $(OMODEL)/olamplot.f90 \
             $(OMODEL)/olam_run.F90 \
             $(OMODEL)/olhi.f90 \
             $(OMODEL)/omic_coll.f90 \
             $(OMODEL)/omic_driv.f90 \
             $(OMODEL)/omic_gamma.f90 \
             $(OMODEL)/omic_init.f90 \
             $(OMODEL)/omic_misc.f90 \
             $(OMODEL)/omic_nuc.f90  \
             $(OMODEL)/omic_parcel.f90  \
             $(OMODEL)/omic_tabs.f90 \
             $(OMODEL)/omic_vap.f90 \
             $(OMODEL)/oname_check.f90 \
             $(OMODEL)/oname.f90 \
             $(OMODEL)/oplot_interface.F90 \
             $(OMODEL)/oplot_lib.f90 \
             $(OMODEL)/othrm.f90 \
             $(OMODEL)/para_decomp.f90 \
             $(OMODEL)/prog_wrtv_orig.f90 \
             $(OMODEL)/prog_wrtv_rk.f90 \
             $(OMODEL)/salt_dust_src.f90 \
             $(OMODEL)/scalar_transport_orig.F90 \
             $(OMODEL)/scalar_transport_rk.F90 \
             $(OMODEL)/spawn_nest.f90 \
             $(OMODEL)/spring_dynamics.f90 \
             $(OMODEL)/surface_fluxes.F90 \
             $(OMODEL)/tileslab.F90 \
             $(OMODEL)/timeseries_plots.f90 \
             $(OMODEL)/timestep.f90 \
             $(OMODEL)/triangle_utils.f90 \
             $(OMODEL)/vectslab.F90 \
             $(OMODEL)/vel_t3d.f90 \
             $(OMODEL)/vort_div_damp.f90 \
             $(OUTILS)/blas.f90 \
             $(OUTILS)/check_nans.F90 \
             $(OUTILS)/dateutils.f90 \
             $(OUTILS)/hdf5_f2f.F90 \
             $(OUTILS)/hdf5_utils.F90 \
             $(OUTILS)/interp_lib.f90 \
             $(OUTILS)/lapack.f90 \
             $(OUTILS)/latlon_bins.f90 \
             $(OUTILS)/map_proj.f90 \
             $(OUTILS)/matrix.f90 \
             $(OUTILS)/olam_interp_ll.f90 \
             $(OUTILS)/o_ncar.f90 \
             $(OUTILS)/polygon_overlap.F90 \
             $(OUTILS)/prfill.f90 \
             $(OUTILS)/quadrature.f90 \
             $(OUTILS)/string_lib.f90 \
             $(OUTILS)/sys_utils.f90 \
             $(OUTILS)/therm_lib.f90 \
             $(OUTILS)/tridiag_lib.f90 \
             $(RADIATE)/cloud_frac.f90 \
             $(RADIATE)/cloudprep_rad.f90 \
             $(RADIATE)/clouds_gno.f90 \
             $(RADIATE)/mem_mclat.f90 \
             $(RADIATE)/mem_radiate.f90 \
             $(RADIATE)/rad_driv.F90 \
             $(RADIATE)/rrtmg_cloud_optics.f90 \
             $(RADIATE)/rrtmg_raddriv.f90 \
             $(RADIATE)/rrtmg_lw/mcica_subcol_gen_lw.f90 \
             $(RADIATE)/rrtmg_lw/parkind.f90 \
             $(RADIATE)/rrtmg_lw/parrrtm.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_cld.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_con.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg01.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg02.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg03.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg04.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg05.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg06.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg07.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg08.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg09.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg10.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg11.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg12.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg13.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg14.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg15.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_kg16.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_ncpar.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_ref.f90 \
             $(RADIATE)/rrtmg_lw/rrlw_wvn.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_cldprmc.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_init.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_rad.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_read_h5.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_rtrnmc.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_setcoef.f90 \
             $(RADIATE)/rrtmg_lw/rrtmg_lw_taumol.f90 \
             $(RADIATE)/rrtmg_sw/mcica_subcol_gen_sw.f90 \
             $(RADIATE)/rrtmg_sw/parrrsw.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_aer.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_cld.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_con.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg16.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg17.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg18.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg19.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg20.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg21.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg22.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg23.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg24.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg25.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg26.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg27.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg28.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_kg29.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_ncpar.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_ref.f90 \
             $(RADIATE)/rrtmg_sw/rrsw_wvn.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_cldprmc.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_init.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_rad.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_read_h5.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_setcoef.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_spcvmc.f90 \
             $(RADIATE)/rrtmg_sw/rrtmg_sw_taumol.f90 \
             $(SEA)/mem_sea.f90 \
             $(SEA)/pom_interface.f90 \
             $(SEA)/pom2k1d.f90 \
             $(SEA)/read_seaice_analysis.F90 \
             $(SEA)/read_sst_analysis.F90 \
             $(SEA)/sea_coms.f90 \
             $(SEA)/sea.f90 \
             $(SEA)/seaice_database_read.f90 \
             $(SEA)/seaice.f90 \
             $(SEA)/sea_init_atm.f90 \
             $(SEA)/sea_startup.f90 \
             $(SEA)/sea_swm.f90 \
             $(SEA)/sst_database_read.f90 \
             $(SFCG)/init_sfcgrid.f90 \
             $(SFCG)/hex_grid_sfc.f90 \
             $(SFCG)/makesfc3.f90 \
             $(SFCG)/mem_sfcg.f90 \
             $(SFCG)/mem_sfcnud.f90 \
             $(SFCG)/olam_mpi_sfc.F90 \
             $(SFCG)/surface_driver.F90 \
             $(HURRICANE)/hurricane_init.F90 \
             $(HURRICANE)/plot_trajecfile.f90 \
             $(TEST_CASES)/mem_swtc5_refsoln_cubic.f90 \
             $(TEST_CASES)/swtc_init.f90 \
             $(TEST_CASES)/diagn_global_swtc.F90 \
             $(TEST_CASES)/dcmip_initial_conditions_test_1_2_3_v5.f90 \
             $(TEST_CASES)/dcmip_initial_conditions_test_4_v2_1.f90 \
             $(TEST_CASES)/test2xdeep.f90 \
             $(TEST_CASES)/test41alt.f90 \
             $(TEST_CASES)/DCMIP2016/baroclinic_wave_test.f90 \
             $(TEST_CASES)/DCMIP2016/diagn_global_dcmip.F90 \
             $(TEST_CASES)/DCMIP2016/kessler.f90 \
             $(TEST_CASES)/DCMIP2016/olam_dcmip3.f90 \
             $(TEST_CASES)/DCMIP2016/dcmip_physics_z_v1.f90 \
             $(TEST_CASES)/DCMIP2016/supercell_test.f90 \
             $(TEST_CASES)/DCMIP2016/Terminator.f90 \
             $(TEST_CASES)/DCMIP2016/tropical_cyclone_test.f90 \
             $(CMAQ)/AERO_DATA.F \
             $(CMAQ)/aero_depv.F \
             $(CMAQ)/aero_driver.F \
             $(CMAQ)/AERO_EMIS.F \
             $(CMAQ)/AERO_PHOTDATA.F \
             $(CMAQ)/AEROSOL_CHEMISTRY.F \
             $(CMAQ)/aero_subs.F \
             $(CMAQ)/AOD_DEFN.F \
             $(CMAQ)/aqchem.F \
             $(CMAQ)/AQ_DATA.F \
             $(CMAQ)/aq_map.F \
             $(CMAQ)/cb6r3_ae6_aq/RXNS_DATA_MODULE.F90 \
             $(CMAQ)/cb6r3_ae6_aq/RXNS_FUNC_MODULE.F90 \
             $(CMAQ)/cgrid_defn.f90 \
             $(CMAQ)/CGRID_SPCS.F \
             $(CMAQ)/cmaq_cloud_optics.f90 \
             $(CMAQ)/cmaq_driver.F90 \
             $(CMAQ)/coags.f \
             $(CMAQ)/CONST_DATA.f90 \
             $(CMAQ)/conv_cgrid.f90 \
             $(CMAQ)/CSQY_DATA.F \
             $(CMAQ)/czangle.F \
             $(CMAQ)/DEPV_DEFN.F \
             $(CMAQ)/DEPVVARS.f90 \
             $(CMAQ)/DUST_EMIS.F \
             $(CMAQ)/edgar_42_emis.F90 \
             $(CMAQ)/EMIS_DEFN.F \
             $(CMAQ)/findex.f \
             $(CMAQ)/gas_depv_map.F \
             $(CMAQ)/geia_emis.F90 \
             $(CMAQ)/getalpha.F \
             $(CMAQ)/getpar.f \
             $(CMAQ)/hlconst.F \
             $(CMAQ)/hrdata_mod.F \
             $(CMAQ)/hrdriver.F \
             $(CMAQ)/hrg1.F \
             $(CMAQ)/hrg2.F \
             $(CMAQ)/hrg3.F \
             $(CMAQ)/hrg4.F \
             $(CMAQ)/hrinit.F \
             $(CMAQ)/hrprodloss.F \
             $(CMAQ)/hrrates.F \
             $(CMAQ)/hrsolver.F \
             $(CMAQ)/indexn.f \
             $(CMAQ)/init_cgrid.f90 \
             $(CMAQ)/isocom.f \
             $(CMAQ)/isofwd.f \
             $(CMAQ)/isorev.f \
             $(CMAQ)/isrpia.f90 \
             $(CMAQ)/LTNG_DEFN.f90 \
             $(CMAQ)/m3dry.f90 \
             $(CMAQ)/oplot_chem_lib.f90 \
             $(CMAQ)/phot_albedo.f90 \
             $(CMAQ)/phot.F \
             $(CMAQ)/PHOT_MOD.F \
             $(CMAQ)/PMDIAG_DATA.F \
             $(CMAQ)/PRECURSOR_DATA.F \
             $(CMAQ)/rescld.f90 \
             $(CMAQ)/scavwdep.F \
             $(CMAQ)/sedv_defn.f90 \
             $(CMAQ)/setup_logdev.F \
             $(CMAQ)/SOA_DEFN.F \
             $(CMAQ)/soil_nox.f90 \
             $(CMAQ)/SSEMIS.F \
             $(CMAQ)/twoway_rrtmg_aero_optics.F90 \
             $(CMAQ)/UTILIO_DEFN.F \
             $(CMAQ)/washout.f90 \
             $(MEGAN)/CONSTS_MEGAN.f90 \
             $(MEGAN)/EMIS_MAPS_MEGAN.f90 \
             $(MEGAN)/megan_driver.F90

