# OLAM root directory.

OLAM_ROOT=$(HOME)/olam

# Versions.

OLAM_VERSION=4.0r

# Source directories.

MODEL_MODS=$(OLAM_ROOT)/$(OLAM_VERSION)/modules
OMODEL=$(OLAM_ROOT)/$(OLAM_VERSION)/omodel
OMODEL_TRI=$(OLAM_ROOT)/$(OLAM_VERSION)/omodel_tri
OMODEL_HEX=$(OLAM_ROOT)/$(OLAM_VERSION)/omodel_hex
OISAN=$(OLAM_ROOT)/$(OLAM_VERSION)/oisan
CONVECT=$(OLAM_ROOT)/$(OLAM_VERSION)/convect
LEAF=$(OLAM_ROOT)/$(OLAM_VERSION)/leaf
SEA=$(OLAM_ROOT)/$(OLAM_VERSION)/sea
ED=$(OLAM_ROOT)/$(OLAM_VERSION)/ed
OUTILS=$(OLAM_ROOT)/$(OLAM_VERSION)/outils
RADIATE=$(OLAM_ROOT)/$(OLAM_VERSION)/radiate
OSPECIAL=$(OLAM_ROOT)/$(OLAM_VERSION)/special
