#Makefile

SOURCE_FILES= \
             $(CONVECT)/cuparm_driver.f90 \
             $(CONVECT)/grell_coms.f90 \
             $(CONVECT)/grell_deep_capmax_ens.f90 \
             $(CONVECT)/grell_deep_coms.f90 \
             $(CONVECT)/grell_downdraft.f90 \
             $(CONVECT)/grell_env_capmax_ens.f90 \
             $(CONVECT)/grell_shallow_capmax_ens.f90 \
             $(CONVECT)/grell_shallow_coms.f90 \
             $(CONVECT)/grell_updraft.f90 \
             $(CONVECT)/kuo.f90 \
             $(CONVECT)/kuo_coms.f90 \
             $(CONVECT)/mem_cuparm.f90 \
             $(ED)/allometry.f90 \
             $(ED)/c34constants.f90 \
             $(ED)/canopy_radiation_coms.f90 \
             $(ED)/decomposition_coms.f90 \
             $(ED)/decomposition.f90 \
             $(ED)/disturbance_coms.f90 \
             $(ED)/disturbance.f90 \
             $(ED)/ed_canopy_update.f90 \
             $(ED)/ed_database.f90 \
             $(ED)/ed_history.f90 \
             $(ED)/ed_init_state_vars.f90 \
             $(ED)/edio.f90 \
             $(ED)/ed_offline_met.f90 \
             $(ED)/ed_options.f90 \
             $(ED)/ed_params.f90 \
             $(ED)/ed_startup.f90 \
             $(ED)/ed_structure_defs.f90 \
             $(ED)/fire.f90 \
             $(ED)/fis_fus_utils.f90 \
             $(ED)/forestry.f90 \
             $(ED)/fusion_fission_coms.f90 \
             $(ED)/growth_balive.f90 \
             $(ED)/landuse_init.f90 \
             $(ED)/lphys_full.f90 \
             $(ED)/lphys_interface.f90 \
             $(ED)/mem_ed.f90 \
             $(ED)/mortality.f90 \
             $(ED)/offline_coms.f90 \
             $(ED)/pft_coms.f90 \
             $(ED)/phenology_coms.f90 \
             $(ED)/phenology.f90 \
             $(ED)/radiate_offline.f90 \
             $(ED)/reproduction.f90 \
             $(ED)/sfcrad_ed.f90 \
             $(ED)/sfluxes_offline.f90 \
             $(ED)/structural_growth.f90 \
             $(ED)/vegetation_dynamics.f90 \
             $(LEAF)/leaf3.f90 \
             $(LEAF)/leaf3_canopy.f90 \
             $(LEAF)/leaf3_init_atm.f90 \
             $(LEAF)/leaf3_landcell.f90 \
             $(LEAF)/leaf3_sfcwater.f90 \
             $(LEAF)/leaf3_soil.f90 \
             $(LEAF)/leaf3_startup.f90 \
             $(LEAF)/leaf_coms.f90 \
             $(LEAF)/leaf_database_read.f90 \
             $(LEAF)/leaf_plot.f90 \
             $(LEAF)/mem_leaf.f90 \
             $(LEAF)/ndvi_database_read.f90 \
             $(LEAF)/olam_mpi_land.F90 \
             $(LEAF)/para_init_land.f90 \
             $(MODEL_MODS)/consts_coms.f90 \
             $(MODEL_MODS)/ke_coms.f90 \
             $(MODEL_MODS)/massflux.f90 \
             $(MODEL_MODS)/max_dims.f90 \
             $(MODEL_MODS)/mem_addsc.f90 \
             $(MODEL_MODS)/mem_basic.f90 \
             $(MODEL_MODS)/mem_grid.f90 \
             $(MODEL_MODS)/mem_ijtabs.f90 \
             $(MODEL_MODS)/mem_mclat.f90 \
             $(MODEL_MODS)/mem_mksfc.f90 \
             $(MODEL_MODS)/mem_micro.f90 \
             $(MODEL_MODS)/mem_nudge.f90 \
             $(MODEL_MODS)/mem_para.f90 \
             $(MODEL_MODS)/mem_rayf.f90 \
             $(MODEL_MODS)/mem_sflux.f90 \
             $(MODEL_MODS)/mem_tend.f90 \
             $(MODEL_MODS)/mem_timeavg.f90 \
             $(MODEL_MODS)/mem_turb.f90 \
             $(MODEL_MODS)/mem_zonavg.f90 \
             $(MODEL_MODS)/micro_coms.f90 \
             $(MODEL_MODS)/misc_coms.f90 \
             $(MODEL_MODS)/olam_mpi_atm.F90 \
             $(MODEL_MODS)/oname_coms.f90 \
             $(MODEL_MODS)/oplot_coms.f90 \
             $(MODEL_MODS)/plotcolors.f90 \
             $(MODEL_MODS)/var_tables.f90 \
             $(OISAN)/asti.f90 \
             $(OISAN)/astp.f90 \
             $(OISAN)/file_inv.f90 \
             $(OISAN)/fldsisan.f90 \
             $(OISAN)/isan_coms.f90 \
             $(OISAN)/isan_driver.f90 \
             $(OMODEL)/alloc.f90 \
             $(OMODEL)/cartesian.f90 \
             $(OMODEL)/contslab.f90 \
             $(OMODEL)/fill_itabs.f90 \
             $(OMODEL)/history_start.f90 \
             $(OMODEL)/history_write.f90 \
             $(OMODEL)/icosahedron.f90 \
             $(OMODEL)/makesfc.f90 \
             $(OMODEL)/obnd.f90 \
             $(OMODEL)/ocio.f90 \
             $(OMODEL)/ohhi.f90 \
             $(OMODEL)/olam_grid.f90 \
             $(OMODEL)/olammain.F90 \
             $(OMODEL)/olamplot.f90 \
             $(OMODEL)/olam_run.F90 \
             $(OMODEL)/olhi.f90 \
             $(OMODEL)/omic_coll.f90 \
             $(OMODEL)/omic_driv.f90 \
             $(OMODEL)/omic_gamma.f90 \
             $(OMODEL)/omic_init.f90 \
             $(OMODEL)/omic_misc.f90 \
             $(OMODEL)/omic_nuc.f90  \
             $(OMODEL)/omic_tabs.f90 \
             $(OMODEL)/omic_vap.f90 \
             $(OMODEL)/oname_check.f90 \
             $(OMODEL)/oname.f90 \
             $(OMODEL)/o_ncar.f90 \
             $(OMODEL)/oplot_interface.f90 \
             $(OMODEL)/oplot_lib.f90 \
             $(OMODEL)/othrm.f90 \
             $(OMODEL)/para_decomp.f90 \
             $(OMODEL)/perim_fill.f90 \
             $(OMODEL)/spawn_nest.f90 \
             $(OMODEL)/spring_dynamics.f90 \
             $(OMODEL)/surface_fluxes.f90 \
             $(OMODEL)/thiltend_long.f90 \
             $(OMODEL)/tileslab.f90 \
             $(OMODEL)/topo_database_read.f90 \
             $(OMODEL)/triangle_utils.f90 \
             $(OMODEL_HEX)/turb_k_hex.f90 \
             $(OMODEL)/vectslab.f90 \
             $(OMODEL_HEX)/hex_grid.f90 \
             $(OMODEL_HEX)/para_init_hex.f90 \
             $(OMODEL_HEX)/prog_wrtv_hex.f90 \
             $(OMODEL_HEX)/scalar_transport_hex.f90 \
             $(OMODEL_HEX)/timestep_hex.f90 \
             $(OMODEL_TRI)/tri_grid.f90 \
             $(OUTILS)/dateutils.f90 \
             $(OUTILS)/filelist.f90 \
             $(OUTILS)/hdf5_f2c.c \
             $(OUTILS)/hdf5_f2f.F90 \
             $(OUTILS)/hdf5_utils.F90 \
             $(OUTILS)/interp_lib.f90 \
             $(OUTILS)/map_proj.f90 \
             $(OUTILS)/read_cdc.c \
             $(OUTILS)/therm_lib.f90 \
             $(OUTILS)/check_nans.F90 \
             $(RADIATE)/ccmp_raddriv.f90 \
             $(RADIATE)/cc_rad.f90 \
             $(RADIATE)/harr_raddriv.f90 \
             $(RADIATE)/harr_rad.f90 \
             $(RADIATE)/harr_radinit.f90 \
             $(RADIATE)/mem_harr.f90 \
             $(RADIATE)/mem_radiate.f90 \
             $(RADIATE)/mp_rad.f90 \
             $(RADIATE)/rad_driv.f90 \
             $(RADIATE)/rad_mclat.f90 \
             $(RADIATE)/rad_stable.f90 \
             $(SEA)/mem_sea.f90 \
             $(SEA)/olam_mpi_sea.F90 \
             $(SEA)/para_init_sea.f90 \
             $(SEA)/sea_coms.f90 \
             $(SEA)/sea.f90 \
             $(SEA)/seaice_database_read.f90 \
             $(SEA)/sea_init_atm.f90 \
             $(SEA)/sea_startup.f90 \
             $(SEA)/sst_database_read.f90
